apiVersion: v1
kind: ConfigMap
metadata:
  name: sovereign-config
data:
  # Internal Service Resolution URLs utilizing Standard Cluster DNS
  DATABASE_URL: "postgresql://dwc_admin:insecure_dev_password@postgres:5432/gamespy"
  REDIS_URL: "redis://redis:6379/0"
  
  # Global application settings
  PYTHONUNBUFFERED: "1"
