apiVersion: apps/v1
kind: Deployment
metadata:
  name: sovereign-dls1
  labels:
    app: sovereign-dls1
spec:
  replicas: 2 # Horizontal scaling redundancy
  selector:
    matchLabels:
      app: sovereign-dls1
  template:
    metadata:
      labels:
        app: sovereign-dls1
    spec:
      containers:
      - name: dls1
        image: project_sovereign_master:latest
        imagePullPolicy: Never
        command: ["python", "dls1_server.py"]
        envFrom:
        - configMapRef:
            name: sovereign-config
        ports:
        - containerPort: 9003
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sovereign-dls1
spec:
  selector:
    app: sovereign-dls1
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
