FROM debian:buster-slim
RUN sed -i 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    sed -i '/buster-updates/d' /etc/apt/sources.list && \
    apt-get update -o Acquire::Check-Valid-Until=false && \
    apt-get install -y python python-twisted sqlite3 && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY reference_repo/ /app/
CMD ["python", "nas_server.py"]
