import asyncio
from gamespy_player_search_server import PlayerSearch
from gamespy.pg_database import PostgresGamespyDatabase
import sys

class MockTransport:
    def write(self, data): 
        print(f"\n>>> SERVER DISPATCHED OUTBOUND NETWORK TRAFFIC: {data}\n")
        self.sent_data = data

def run():
    print("--- COMMENCING THE ULTIMATE FINAL MISSION VERIFICATION ---")
    
    # 1. Prepare Real Test Target inside Postgres
    async def inject():
        db = PostgresGamespyDatabase("postgresql://dwc_admin:insecure_dev_password@localhost:5432/gamespy")
        await db.initialize_database()
        async with db.pool.acquire() as conn:
            await conn.execute("DELETE FROM users WHERE profileid = 777777")
            await conn.execute("""
                INSERT INTO users (profileid, uniquenick, userid, console)
                VALUES (777777, 'ULTIMATE_VICTORY_NICK', 'user-ultimate', 1)
            """)
        await db.close()
    asyncio.run(inject())
    print("[1] Definitive target injected into physical PostgreSQL stores.")
    
    # 2. Instantiate Target Twisted Protocol
    class MockAddr: host = '127.0.0.1'; port = 6666
    
    print("[2] Activating PlayerSearch Protocol instance (Engaging Magical Proxy)...")
    protocol = PlayerSearch(MockAddr())
    protocol.transport = MockTransport()
    
    # 3. Mimic an incoming "Buddy Search" packet targeting the injected ID!
    incoming_parsed_message = {
        '__cmd__': 'otherslist',
        'numopids': '1',
        'opids': '777777'
    }
    
    print("[3] Executing perform_otherslist direct logic injection...")
    try:
        # Trigger the magic! Calls get_profile_from_profileid through proxy automatically!
        protocol.perform_otherslist(incoming_parsed_message)
        print("Execution cycle concluded gracefully!")
    except Exception as e:
        print(f"\n❌ ERROR DETECTED: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
        
    # 4. THE FINAL VERDICT: Inspect the network traffic output generated by the proxy resolution!
    output = protocol.transport.sent_data
    
    if b'ULTIMATE_VICTORY_NICK' in output:
        print("\n✨ THE MAGIC HAS WORKED! ✨")
        print("The final server retrieved data natively from PostgreSQL via the Dynamic Proxy perfectly!")
        print("\n🏆🏆🏆 MISSION ACCOMPLISHED: PHASE 1 STEP 2 IS OFFICIALLY OVER 🏆🏆🏆")
    else:
        print("\n❌ FAILURE: Sent data did not contain the Postgres nickname!")
        sys.exit(1)
    
    # Ultimate Final Cleanup
    protocol.db.close()

if __name__ == "__main__":
    run()
